title: "general blog @ urbansite.si"
author:
  name: "Urban"
  email: "urban@urbansite.si"

remote_theme: mmistakes/minimal-mistakes@4.27.3

minimal_mistakes_skin: "dark"

url: "https://www.urbansite.si"
baseurl: "/blog"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

paginate: 5
paginate_path: /page:num/