title: "Writeups @ urbansite.si"
description: "CTF writeups"
url: "https://www.urbansite.si"
baseurl: "/writeups"

remote_theme: abhinavs/moonwalk
theme_config:
  appearance: dark
  appearance_toggle: true
  date_format: "%B %d, %Y"

permalink: /:title/
paginate: 5
paginate_path: "/page:num"

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
